#!/usr/bin/env python3
"""Build data/chants/kantar-antati.json from kaumaram.com's per-verse pages
(kaumaram.com/anthathi/nat_001.html ... nat_100.html, with Tamil meanings by
'Thiruppugazh adimai' Sri S. Nadarajan).

Each page gives the verse as sung (பாடல்), its word division (சொற்பிரிவு),
word-by-word glosses (பதவுரை), and a prose summary (பொழிப்புரை). Aruṇakirinātar
wrote the Kantar Antāti in yamaka (மடக்கு): the four lines of a verse share
the same sounds but divide into different words, so the sung form is what
the chant displays, and the word division is saved alongside (in the cache
dir, as kantar_antati_aids.json) as a translation aid; it isn't published.

Usage: python3 ingest_kantar_antati.py <cache-dir>
"""
import html
import json
import re
import sys
import time
import urllib.request
from pathlib import Path

from tamil_to_iso import tamil_to_iso

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
BASE = 'https://kaumaram.com/anthathi/'
DATA_DIR = Path(__file__).resolve().parent.parent / 'data' / 'chants'
TOTAL = 100


def page_text(cache: Path, n: int) -> str:
    path = cache / f'kantar_{n:03d}.html'
    if not path.exists():
        req = urllib.request.Request(f'{BASE}nat_{n:03d}.html', headers={'User-Agent': USER_AGENT})
        path.write_bytes(urllib.request.urlopen(req, timeout=30).read())
        time.sleep(0.3)
    raw = path.read_text(encoding='utf-8', errors='replace')
    text = html.unescape(re.sub(r'<[^>]+>', '\n', re.sub(r'<br\s*/?>', '\n', raw)))
    return '\n'.join(l.strip() for l in text.splitlines() if l.strip())


def block(text: str, name: str, stop: str) -> list[str]:
    start = text.index(f'......... {name} .........') + len(f'......... {name} .........')
    end = text.index(stop, start)
    return [l for l in text[start:end].split('\n') if l.strip()]


def clean(line: str) -> str:
    line = re.sub(r'\s*\.{3,}\s*\d+\s*$', '', line)
    return re.sub(r'\s+', ' ', line).strip()


def main(cache: Path):
    sections, aids, n_line = [], {}, 0
    for n in range(1, TOTAL + 1):
        text = page_text(cache, n)
        sung = [clean(l) for l in block(text, 'பாடல்', '.........')]
        split = [clean(l) for l in block(text, 'சொற்பிரிவு', '.........')]
        gloss = block(text, 'பதவுரை', '.........')
        summary = block(text, 'பொழிப்புரை', '-->')
        if len(sung) != 4:
            raise ValueError(f'verse {n}: expected 4 sung lines, got {len(sung)}: {sung}')
        lines = []
        for line in sung:
            n_line += 1
            lines.append({'n': n_line, 'devanagari': line, 'iast': tamil_to_iso(line)})
        sections.append({'label': str(n), 'lines': lines})
        aids[n] = {'split': split, 'gloss': gloss, 'summary': summary}
    chant = {
        'id': 'kantar-antati',
        'language': 'tamil',
        'title': {'devanagari': 'கந்தர் அந்தாதி', 'iast': 'Kantar Antāti'},
        'source': {
            'site': 'kaumaram.com',
            'devanagari_url': BASE,
            'note': ("By Aruṇakirinātar. Tamil text as sung, from kaumaram.com's per-verse pages "
                     "(which carry Tamil word divisions and meanings by 'Thiruppugazh adimai' Sri S. "
                     "Nadarajan, used here as translation aids). ISO 15919 transliteration generated by "
                     "scripts/tamil_to_iso.py; English translation prepared for this app."),
        },
        'sectionUnit': 'Verse',
        'sections': sections,
    }
    (DATA_DIR / 'kantar-antati.json').write_text(json.dumps(chant, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    (cache / 'kantar_antati_aids.json').write_text(json.dumps(aids, ensure_ascii=False, indent=1), encoding='utf-8')
    print(f'kantar-antati: {len(sections)} verses')


if __name__ == '__main__':
    main(Path(sys.argv[1]))
