#!/usr/bin/env python3
"""Build data/chants/<id>.json for nine antātis from Project Madurai's Tamil
Unicode editions (projectmadurai.org/pm_etexts/utf8/):

  pmuni0007     Nālāyira Divya Prabandham part 4: the three Mutal Āḻvārs'
                Tiruvantātis (Mutal 2082-2181, Iraṇṭām 2182-2281,
                Mūṉṟām 2282-2381), Nāṉmukaṉ Tiruvantāti
                (2382-2477), Periya Tiruvantāti (2585-2671), Irāmānuca
                Nūṟṟantāti (2791 on)
  pmuni0126     11th Tirumurai part 1: Tiruvirattai Maṇimālai (24-43),
                Poṉvaṇṇattantāti (169-269)
  pmuni0127_02  11th Tirumurai part 2: Tiruttoṇṭar Tiruvantāti (1126-1215)

Two layouts occur. Most works give every verse a running-number header
("2382:" or "169."), so verses are cut at those headers. The Irāmānuca
Nūṟṟantāti drops the headers after its sixth verse and marks each verse
only with its within-work number at the end of its last line, so it is cut
at those trailing numbers instead. Either way the within-work verse number
becomes the section label, and the recitation marks the edition carries
((2) = "sung twice", and * pause marks) are dropped. Tamil text is kept in
the edition's own metrical word-division; IAST is generated by
tamil_to_iso.py.

Usage: python3 ingest_pm_antatis.py <cache-dir>   (cache-dir holds the
downloaded pmuniNNNN.html files; they're fetched if missing)
"""
import html
import json
import re
import sys
import urllib.request
from pathlib import Path

from tamil_to_iso import tamil_to_iso

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
BASE = 'https://www.projectmadurai.org/pm_etexts/utf8/'
DATA_DIR = Path(__file__).resolve().parent.parent / 'data' / 'chants'

WORKS = [
    {
        'id': 'mudhal-tiruvantati', 'file': 'pmuni0007', 'first': 2082, 'last': 2181,
        'title': 'முதல் திருவந்தாதி', 'title_iast': 'Mutal Tiruvantāti',
        'author': 'Poykai Āḻvār', 'colophon': 'பொய்கையாழ்வார் திருவடிகளே சரணம்',
        # The dropped நு/நூ ligature ("_"), plus misprints checked against the
        # koyil.org text and the standard recitation: ே printed as ோ (v.8
        # தேராழி "chariot wheel", v.20 பேர்ந்து, v.24 தேங்கி), a dropped
        # syllable (v.23 தோய்ந்தவா மங்கை), and ி for ு (v.70 ஏத்துதிரேல்).
        'fixes': {'உரை_ல்': 'உரைநூல்', '_ண்கேள்வி': 'நுண்கேள்வி', 'வெண்புரி_ல்': 'வெண்புரிநூல்',
                  '_டங்கிடையை': 'நுடங்கிடையை', 'தோராழி': 'தேராழி', 'போர்ந்தோர்': 'பேர்ந்தோர்',
                  'தோங்கி நினைந்த': 'தேங்கி நினைந்த', 'தோய்ந்த மங்கை': 'தோய்ந்தவா மங்கை',
                  'ஏத்திதிரேல்': 'ஏத்துதிரேல்'},
    },
    {
        'id': 'irandam-tiruvantati', 'file': 'pmuni0007', 'first': 2182, 'last': 2281,
        'title': 'இரண்டாம் திருவந்தாதி', 'title_iast': 'Iraṇṭām Tiruvantāti',
        'author': 'Pūtattāḻvār', 'colophon': 'பூதத்தாழ்வார் திருவடிகளே சரணம்',
        # v.1's famous opening, அன்பே தகளியா ("love as the lamp's saucer"),
        # printed without its க; v.12 ஒண்மலரோன் (Brahmā "on the bright
        # flower"); v.73 ஆதி நடு அந்தி ("beginning, middle, end"); v.74
        # இருந்தமிழ் ("great Tamil"); v.75 dative மாப்பிடிக்கு; v.88 திறம்பா
        # வழி ("the unswerving path").
        'fixes': {'ஈரைஞ்_': 'ஈரைஞ்ஞூ', 'அன்பே தளியா': 'அன்பே தகளியா', 'ரோ னெண்மலரோன்': 'ரோ னொண்மலரோன்',
                  'ஆய்நடு': 'ஆதிநடு', 'இருந்ததமிழ்நன்': 'இருந்தமிழ்நன்', 'மாப்பிடிக்கி': 'மாப்பிடிக்கு',
                  'வருசென்றார்க்': 'வழிசென்றார்க்'},
    },
    {
        'id': 'munram-tiruvantati', 'file': 'pmuni0007', 'first': 2282, 'last': 2381,
        'title': 'மூன்றாம் திருவந்தாதி', 'title_iast': 'Mūṉṟām Tiruvantāti',
        'author': 'Pēyāḻvār', 'colophon': 'பேயாழ்வார் திருவடிகளே சரணம்',
        # v.30 மறைப்பாடகம் (the shrine Tiruppāṭakam, printed மறையாடகம்);
        # v.57 பொலிந்திருண்ட ("dark," printed இருகண்ட).
        'fixes': {'_ற்கடலான் _ண்ணறிவி': 'நூற்கடலான் நுண்ணறிவி', '_ற்பால்': 'நூற்பால்',
                  '_ற்கடலும் _ண்ணுல': 'நூற்கடலும் நுண்ணுல', 'ரைஞ்_': 'ரைஞ்ஞூ',
                  'மறையா டகம்': 'மறைப்பா டகம்', 'பொலிந்திருகண்ட': 'பொலிந்திருண்ட'},
    },
    {
        'id': 'nanmukan-tiruvantati', 'file': 'pmuni0007', 'first': 2382, 'last': 2477,
        'title': 'நான்முகன் திருவந்தாதி', 'title_iast': 'Nāṉmukaṉ Tiruvantāti',
        'author': 'Tirumaḻicai Āḻvār', 'colophon': 'திருமழிசையாழ்வார் திருவடிகளே சரணம்',
        # The edition's font drops the நு/நூ ligature, printing "_" instead.
        'fixes': {'வில்_டங்க': 'வில்நுடங்க', '_ல்வலையில்': 'நூல்வலையில்', '_லாட்டி': 'நூலாட்டி'},
    },
    {
        'id': 'periya-tiruvantati', 'file': 'pmuni0007', 'first': 2585, 'last': 2671,
        'title': 'பெரிய திருவந்தாதி', 'title_iast': 'Periya Tiruvantāti',
        'author': 'Nammāḻvār', 'colophon': 'நம்மாழ்வார் திருவடிகளே சரணம்',
        'fixes': {'_ண்புடையீர் _ம்மை _மக்கு': 'நுண்புடையீர் நும்மை நுமக்கு', '_மக்கடியோம்': 'நுமக்கடியோம்'},
    },
    {
        'id': 'ramanuja-nurrantati', 'file': 'pmuni0007', 'first': 2791, 'count': 108, 'trailing': True,
        'start_marker': 'இராமாநுச நூற்றந்தாதி',
        'title': 'இராமாநுச நூற்றந்தாதி', 'title_iast': 'Irāmānuca Nūṟṟantāti',
        'author': 'Tiruvaraṅkattu Amutaṉār', 'colophon': 'திருவரங்கத்தமுதனார் திருவடிகளே சரணம்',
        # Edition typos: the saint's own name misprinted twice (v.1, v.60),
        # and a word printed twice in v.96.
        'fixes': {'தாம்மன்னவந்தவிராமாது சன்': 'தாம்மன்னவந்தவிராமாநுசன்', 'இராமாநுகன்': 'இராமாநுசன்', 'முடைத்தலையூன் முடைத்தலயூன்': 'முடைத்தலையூன்'},
    },
    {
        'id': 'tiruvirattai-manimalai', 'file': 'pmuni0126', 'first': 24, 'last': 43,
        'title': 'திருஇரட்டை மணிமாலை', 'title_iast': 'Tiruiraṭṭai Maṇimālai',
        'author': 'Kāraikkāl Ammaiyār', 'colophon': 'திருச்சிற்றம்பலம்',
    },
    {
        'id': 'ponvannattantati', 'file': 'pmuni0126', 'first': 169, 'last': 269,
        'title': 'பொன்வண்ணத்தந்தாதி', 'title_iast': 'Poṉvaṇṇattantāti',
        'author': 'Cēramāṉ Perumāḷ Nāyaṉār', 'colophon': 'திருச்சிற்றம்பலம்',
    },
    {
        'id': 'tiruttondar-tiruvantati', 'file': 'pmuni0127_02', 'first': 1126, 'last': 1215,
        'title': 'திருத்தொண்டர் திருவந்தாதி', 'title_iast': 'Tiruttoṇṭar Tiruvantāti',
        'author': 'Nampiyāṇṭār Nampi', 'colophon': 'திருச்சிற்றம்பலம்', 'named_headers': True,
    },
]

TRAILING_NUM = re.compile(r'[\s.]*\(?\d+\)?\s*$')


def load(cache: Path, name: str) -> str:
    path = cache / f'{name}.html'
    if not path.exists():
        req = urllib.request.Request(BASE + name + '.html', headers={'User-Agent': USER_AGENT})
        path.write_bytes(urllib.request.urlopen(req, timeout=30).read())
    raw = path.read_text(encoding='utf-8', errors='replace')
    return html.unescape(re.sub(r'<[^>]+>', '', re.sub(r'<br\s*/?>', '\n', raw)))


def clean(line: str) -> str:
    if not re.search('[\u0B80-\u0BFF]', line):
        return ''
    line = line.replace('*', '')
    line = re.sub(r'\(\s*2\s*\)', '', line)
    line = TRAILING_NUM.sub('', line)
    return re.sub(r'\s+', ' ', line).strip().rstrip('.').strip()


def by_headers(text: str, work: dict):
    """Cut at running-number headers ("2382:", "169.", "1127 <name>")."""
    verses = []
    start = None
    for n in range(work['first'], work['last'] + 1):
        m = re.search(rf'(?m)^[ \t]*{n}[ \t]*[:.]?[ \t]*([^\n]*)$', text[start or 0:] if start else text)
        if not m:
            raise ValueError(f"{work['id']}: header {n} not found")
        pos = (start or 0) + m.start() if start else m.start()
        verses.append((n, pos, m.group(1).strip()))
        start = pos + len(m.group(0))
    out = []
    for k, (n, pos, heading) in enumerate(verses):
        body_start = text.index('\n', pos) + 1
        body_end = verses[k + 1][1] if k + 1 < len(verses) else body_start + 2000
        lines = [clean(l) for l in text[body_start:body_end].split('\n')]
        lines = [l for l in lines if l and not re.search(r'திருவடிகளே சரணம்|திருச்சிற்றம்பலம்|^-+$|அருளிச்|ஆக்கியோன் பெயர்', l)]
        out.append({'n': k + 1, 'heading': heading if work.get('named_headers') else '', 'lines': lines[:4]})
    return out


def by_trailing_numbers(text: str, work: dict):
    """Cut where a line ends in the next within-work verse number."""
    seg = text[text.index(work['start_marker']):]
    seg = seg[seg.index(f"{work['first']}:"):]
    out, buf, expect = [], [], 1
    for raw in seg.split('\n'):
        raw_s = raw.strip()
        if not raw_s or re.fullmatch(r'\d{4}\s*:', raw_s):
            continue
        m = re.search(r'(\d+)\s*$', raw_s)
        buf.append(raw_s)
        # The edition skips a number once (its verse after 85 is printed
        # "87"), so accept a small jump; numbering here is by position, and
        # the antāti chain check in main() confirms nothing was dropped.
        if m and expect <= int(m.group(1)) <= expect + 1 and len([b for b in buf if clean(b)]) >= 4:
            if int(m.group(1)) != expect:
                print(f"  note: {work['id']} verse {expect} is printed as {m.group(1)}")
            out.append({'n': expect, 'heading': '', 'lines': [clean(l) for l in buf if clean(l)][:4]})
            buf, expect = [], expect + 1
            if expect > work['count']:
                break
    if len(out) != work['count']:
        raise ValueError(f"{work['id']}: got {len(out)} verses, expected {work['count']}")
    return out


def build(work: dict, text: str) -> dict:
    verses = by_trailing_numbers(text, work) if work.get('trailing') else by_headers(text, work)
    sections = []
    n = 0
    for v in verses:
        label = str(v['n'])
        if v['heading']:
            label = f"{v['n']} · {tamil_to_iso(v['heading']).title()}"
        lines = []
        for l in v['lines']:
            for bad, good in work.get('fixes', {}).items():
                l = l.replace(bad, good)
            n += 1
            lines.append({'n': n, 'devanagari': l, 'iast': tamil_to_iso(l)})
        sections.append({'label': label, 'lines': lines})
    return {
        'id': work['id'],
        'language': 'tamil',
        'title': {'devanagari': work['title'], 'iast': work['title_iast']},
        'source': {
            'site': 'projectmadurai.org',
            'devanagari_url': BASE + work['file'] + '.html',
            'note': (f"By {work['author']}. Tamil text from Project Madurai's Unicode edition, in its own "
                     "metrical word-division, with its recitation marks ((2), *) dropped"
                     + (f" and these typos corrected: {'; '.join(f'{a} → {b}' for a, b in work['fixes'].items())}" if work.get('fixes') else '')
                     + ". ISO 15919 "
                     "transliteration generated by scripts/tamil_to_iso.py; English translation prepared "
                     "for this app."),
        },
        'colophon': {'devanagari': work['colophon'], 'iast': tamil_to_iso(work['colophon'])},
        'sectionUnit': '' if work.get('named_headers') else 'Verse',
        'sections': sections,
    }


if __name__ == '__main__':
    cache = Path(sys.argv[1])
    only = set(sys.argv[2:])
    texts = {}
    for work in WORKS:
        if only and work['id'] not in only:
            continue
        texts.setdefault(work['file'], load(cache, work['file']))
        chant = build(work, texts[work['file']])
        short = [s['label'] for s in chant['sections'] if len(s['lines']) != 4]
        # Antāti chain check: each verse should open with (roughly) the last
        # word of the previous one — compare the first two letters, which
        # survive the small sandhi changes at the join.
        secs = chant['sections']
        broken = []
        for a, b in zip(secs, secs[1:]):
            if not a['lines'] or not b['lines']:
                continue
            last = re.sub(r'[^\u0B80-\u0BFF]', ' ', a['lines'][-1]['devanagari']).split()[-1]
            first = re.sub(r'[^\u0B80-\u0BFF]', ' ', b['lines'][0]['devanagari']).split()[0]
            if last[:2] != first[:2]:
                broken.append(f"{a['label']}→{b['label']} ({last}/{first})")
        print(f"  chain breaks: {broken[:8]}{' ...' if len(broken) > 8 else ''} ({len(broken)})")
        (DATA_DIR / f"{work['id']}.json").write_text(json.dumps(chant, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f"{work['id']}: {len(chant['sections'])} verses; non-4-line verses: {short}")
